export const phone = '+60103907390'
export const wa = '60103907390'
export const email = 'ekaradesign23@gmail.com'
export const maps = 'https://www.google.com/maps/place/Ekara+Design/@3.1963226,101.7069851,17z'
export const facebook = 'https://facebook.com/112933178458369'
export const instagram = 'https://www.instagram.com/ekara_design_studio/'
export const pitchWa = 'https://wa.me/601151198497'
export const asset = (path: string) => `${import.meta.env.BASE_URL}${path.replace(/^\//, '')}`

export const projects = [
  { titleEN: 'Setapak Soft Living', titleMS: 'Ruang Tamu Lembut Setapak', typeEN: 'Living room', typeMS: 'Ruang tamu', img: 'images/p1.jpg' },
  { titleEN: 'Calm Bedroom Suite', titleMS: 'Suite Bilik Tidur Tenang', typeEN: 'Bedroom makeover', typeMS: 'Ubah suai bilik tidur', img: 'images/p2.jpg' },
  { titleEN: 'Wall & Décor Story', titleMS: 'Cerita Dinding & Dekorasi', typeEN: 'Wall styling', typeMS: 'Styling dinding', img: 'images/p3.jpg' },
  { titleEN: 'Light Kitchen Corner', titleMS: 'Sudut Dapur Cerah', typeEN: 'Kitchen', typeMS: 'Dapur', img: 'images/p4.jpg' },
  { titleEN: 'Dining in Sage', titleMS: 'Ruang Makan Sage', typeEN: 'Dining', typeMS: 'Ruang makan', img: 'images/p5.jpg' },
  { titleEN: 'Home Office Nook', titleMS: 'Sudut Pejabat Rumah', typeEN: 'Work corner', typeMS: 'Sudut kerja', img: 'images/p6.jpg' },
]

export const dict = {
  en: {
    nav_about: 'About', nav_services: 'Services', nav_work: 'Work', nav_process: 'Process', nav_contact: 'Contact', nav_cta: 'Chat on WhatsApp',
    hero_kicker: 'Setapak · Diamond Square · KL',
    hero_title: 'Soft light. Clean finishes. A home that exhales.',
    hero_sub: 'Friendly guidance in Setapak — from wall styling to full makeovers — with workmanship clients still talk about.',
    hero_cta: 'WhatsApp Ekara', hero_cta2: 'View examples',
    about_label: 'Our studio', about_title: 'Design advice that feels like a trusted friend.',
    about_body: 'Ekara Design is an interior design studio in Setapak / Diamond Square, Kuala Lumpur. Clients praise clear guidance, clean workmanship, and designs that match their taste — from wall decoration to full bedroom and home makeovers.',
    about_rating: '5.0 Google · 10 reviews',
    services_label: 'Services', services_title: 'Rooms that welcome you home.',
    svc1_t: 'Residential interior design', svc1_b: 'Layouts and moods that fit how your household actually lives.',
    svc2_t: 'Wall & décor styling', svc2_b: 'Feature walls, finishes, and décor that pull a room together.',
    svc3_t: 'Bedroom makeovers', svc3_b: 'Restful suites with thoughtful storage and soft lighting.',
    svc4_t: 'Consultation & planning', svc4_b: 'Clear advice so you know what to do next — and why.',
    work_label: 'Inspiration', work_title: 'Quiet inspiration',
    work_note: 'Example visuals for this concept site — not claimed as completed Ekara projects.',
    process_label: 'Process', process_title: 'Simple steps to a home you love.',
    step1_t: 'Consult', step1_b: 'We listen to your taste, budget, and space constraints.',
    step2_t: 'Plan', step2_b: 'Ideas, materials, and a clear path forward.',
    step3_t: 'Style & build', step3_b: 'Clean workmanship with attention to the details that matter.',
    step4_t: 'Enjoy', step4_b: 'A finished home that feels welcoming every day.',
    testimonials_label: 'What clients say', testimonials_title: 'Real words from Google reviews.',
    t1: 'Helped design my house wall decoration. So satisfied with the result.',
    t2: 'Great guidance on décor ideas… cleanliness of work and workmanship stood out.',
    t3: 'Good service — efficient, friendly, and skilled at matching client taste.',
    t4: 'Trusted and understanding consultant.',
    contact_label: 'Get in touch', contact_title: 'Shall we refresh a room together?',
    contact_hours: 'Mon–Fri 10:00 AM – 6:00 PM · Sat 10:00 AM – 2:00 PM · Sun closed',
    contact_address: 'A-G-03, Office Lot, Diamond Residences, Diamond Square, 53100 Kuala Lumpur',
    contact_phone: 'Call', contact_wa: 'WhatsApp', contact_email: 'Email', contact_map: 'Maps', contact_fb: 'Facebook', contact_ig: 'Instagram',
    footer_pitch: 'Website concept prepared for this studio. Not an official site yet — open to making it yours.',
    footer_pitch_cta: 'Message mr.bagowabair', footer_copy: '© Ekara Design · Concept site',
    lang_en: 'EN', lang_ms: 'BM', sticky_wa: 'WhatsApp', menu_open: 'Menu', menu_close: 'Close',
  },
  ms: {
    nav_about: 'Tentang', nav_services: 'Perkhidmatan', nav_work: 'Kerja', nav_process: 'Proses', nav_contact: 'Hubungi', nav_cta: 'Chat WhatsApp',
    hero_kicker: 'Setapak · Diamond Square · KL',
    hero_title: 'Cahaya lembut. Kemasan kemas. Rumah yang tenang.',
    hero_sub: 'Panduan mesra di Setapak — dari styling dinding hingga ubah suai penuh — dengan kemasan yang masih dipuji pelanggan.',
    hero_cta: 'WhatsApp Ekara', hero_cta2: 'Lihat contoh',
    about_label: 'Studio kami', about_title: 'Nasihat reka bentuk yang rasanya seperti kawan dipercayai.',
    about_body: 'Ekara Design ialah studio reka bentuk dalaman di Setapak / Diamond Square, Kuala Lumpur. Pelanggan memuji panduan yang jelas, kerja yang kemas, dan reka bentuk yang menepati citarasa — dari hiasan dinding hingga bilik tidur dan rumah penuh.',
    about_rating: '5.0 Google · 10 ulasan',
    services_label: 'Perkhidmatan', services_title: 'Bilik yang menyambut anda pulang.',
    svc1_t: 'Reka bentuk kediaman', svc1_b: 'Susun atur dan mood yang sesuai dengan cara isi rumah anda hidup.',
    svc2_t: 'Styling dinding & dekorasi', svc2_b: 'Dinding ciri, kemasan, dan dekorasi yang menyatukan bilik.',
    svc3_t: 'Ubah suai bilik tidur', svc3_b: 'Suite tenang dengan storan bijak dan pencahayaan lembut.',
    svc4_t: 'Perundingan & perancangan', svc4_b: 'Nasihat jelas supaya anda tahu langkah seterusnya — dan kenapa.',
    work_label: 'Inspirasi', work_title: 'Inspirasi tenang',
    work_note: 'Visual contoh untuk laman konsep ini — bukan projek siap Ekara yang didakwa.',
    process_label: 'Proses', process_title: 'Langkah mudah ke rumah yang anda sayang.',
    step1_t: 'Runding', step1_b: 'Kami dengar citarasa, bajet, dan kekangan ruang anda.',
    step2_t: 'Rancang', step2_b: 'Idea, bahan, dan hala tuju yang jelas.',
    step3_t: 'Styling & bina', step3_b: 'Kerja kemas dengan perhatian pada perincian penting.',
    step4_t: 'Nikmati', step4_b: 'Rumah siap yang mesra setiap hari.',
    testimonials_label: 'Kata pelanggan', testimonials_title: 'Ulasan sebenar dari Google.',
    t1: 'Bantu reka hiasan dinding rumah. Sangat puas hati dengan hasilnya.',
    t2: 'Panduan idea dekorasi sangat baik… kebersihan kerja dan workmanship menonjol.',
    t3: 'Servis bagus — cekap, mesra, dan pandai penuhi citarasa pelanggan.',
    t4: 'Perunding yang dipercayai dan memahami.',
    contact_label: 'Hubungi kami', contact_title: 'Mari segarkan satu bilik bersama?',
    contact_hours: 'Isnin–Jumaat 10:00 pagi – 6:00 petang · Sabtu 10:00 pagi – 2:00 petang · Ahad tutup',
    contact_address: 'A-G-03, Office Lot, Diamond Residences, Diamond Square, 53100 Kuala Lumpur',
    contact_phone: 'Telefon', contact_wa: 'WhatsApp', contact_email: 'E-mel', contact_map: 'Maps', contact_fb: 'Facebook', contact_ig: 'Instagram',
    footer_pitch: 'Konsep laman web disediakan untuk studio ini. Bukan laman rasmi lagi — sedia dijadikan milik anda.',
    footer_pitch_cta: 'Mesej mr.bagowabair', footer_copy: '© Ekara Design · Laman konsep',
    lang_en: 'EN', lang_ms: 'BM', sticky_wa: 'WhatsApp', menu_open: 'Menu', menu_close: 'Tutup',
  },
} as const
